version: "3.7"

services:
  store:
    container_name: store
    image: samply/blaze:develop
    environment:
      BASE_URL: "http://store:8080"

  test-data-loader:
    container_name: test-data-loader
    image: samply/test-data-loader
    environment:
      FHIR_STORE_URL: "http://store:8080/fhir"
      PATIENT_COUNT: "2000"
    command: sh -c "sleep 60 && /app/run.sh" # wait for Blaze to start

  transfair:
    container_name: transfair
    image: samply/transfair
    environment:
      TF_FHIR_SERVER_SOURCE_ADDRESS: "http://store:8080/fhir"
      TF_PROFILE: "BBMRI2BEACON"
      TF_BEACON_MONGO_USER: "root"
      TF_BEACON_MONGO_PASS: "example"
      TF_TIMER_CRON: "0/59 * * * *"
    volumes:
      - ./bff:/data
    restart: on-failure
    command: sh -c "sleep 180 && java -jar transFAIR.jar" # Wait for test-data-loader

  db-beacon:
    image: mongo:5
    hostname: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  beacon:
    build: ..
    image: egarchive/beacon:2.0
    hostname: beacon
    container_name: beacon
    volumes:
      - ./images/beacon2-ri-api/deploy/conf.py:/beacon/beacon/conf.py
      - ./images/beacon2-ri-api/deploy/logger.yml:/beacon/beacon/logger.yml
      - ./images/beacon2-ri-api/deploy/ontologies:/beacon/ontologies
    ports:
      - "5050:5050"
    working_dir: '/beacon'
    entrypoint: ['python','-m','beacon']

